export const GET_TOP_RESTAURANTS = 'GET_TOP_RESTAURANTS';
export const RESTAURANT_ERROR = 'RESTAURANT_ERROR';
export const GET_TOP_DISHES = 'GET_TOP_DISHES';
export const DISHES_ERROR = 'DISHES_ERROR';
export const CHEFS_ERROR = 'CHEFS_ERROR';
export const GET_ALL_CHEFS = 'GET_ALL_CHEFS';
export const GET_RESTAURANTS_BY_CHEF = 'GET_RESTAURANTS_BY_CHEF';
export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const GET_RESTAURANT_BY_ID = 'GET_RESTAURANT_BY_ID';
export const GET_ALL_DISHES = 'GET_ALL_DISHES';
export const GET_DISH_BY_ID = 'GET_DISH_BY_ID';
export const DELETE_DISH_BY_ID = 'DELETE_DISH_BY_ID';

