export const GET_TOP_RESTAURANTS = 'GET_TOP_RESTAURANTS';
export const RESTAURANT_ERROR = 'RESTAURANT_ERROR';
export const GET_TOP_DISHES = 'GET_TOP_DISHES';
export const DISHES_ERROR = 'DISHES_ERROR';

